config/routes.rb
Rails.application.routes.draw do

  scope ":locale", defaults: {locale: Rails.application.secrets.default_locale}, :path_prefix => '/:locale' do
    ActiveAdmin.routes(self)
  end
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  post "/stripe_webhook" => "memberships#stripe_webhook"
  post "/paypal_webhook" => "memberships#paypal_webhook"
  scope "(:locale)", locale: /ar|en|sv/, defaults: { locale: Rails.application.secrets.default_locale } do
    devise_for :admin_users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users, skip: :omniauth_callbacks
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "home#dashboard"
    post "/hook" => "memberships#hook"

    resources :home do
      collection do
        put 'update_locale'
        get 'leader_board'
      end
    end

    resources :categories do
      collection do
        get 'get_quizzes'
      end
    end
    
    resources :feedbacks
    
    resources :faq_categories do
      member do
        get 'get_questions'
      end
    end
    
    resources :quizzes do
      member do
        get 'attempted_questions'
        get 'view_questions'
      end
      collection do
        get 'challenge_bank'
      end
    end
    
    resources :scorecards
    resources :subscriptions, only: [:new, :create, :index] do
      collection do
        post 'webhook'
      end
    end
    
    resources :reports do
      member do
        patch 'update_report'
      end
    end
    resources :memberships
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user
  before_action :check_subscriptions, :except => [:challenge_bank]

  def show
    @quiz = Quiz.find(params[:id])
    has_subscription = current_user.has_subscription?

    if current_user.guest? && @quiz.quiz_type == "paid"
      flash[:danger] = 'You Need to SignUp and Subscribe first.'
      redirect_to root_path
    elsif (has_subscription.blank? && @quiz.quiz_type == "paid")
      flash[:danger] = 'You Need to Subscribe first.'
      redirect_to root_path
    else
      @questions = @quiz.questions.active
      @pass_score = @quiz.pass_score
      @passing_percent = (@pass_score * 100)/ (@questions.count) if ( @pass_score.present? && @questions.present?)
      @mistakes_allowed = @questions.count - @pass_score
      @scorecard = @current_user.scorecards.find_by_quiz_id(@quiz.id)
      @reports = @scorecard.present? ? @scorecard.reports : []
      if @scorecard.present?
        @question = @questions.order('id asc').where.not('id in (?)', @reports.pluck(:question_id)).first if @questions.present?
      else
        @question = @questions.first
      end

      @wrong_answer_reports = Report.joins(:scorecard, :answer).where("scorecards.user_id = ? and answers.correct = ?", @current_user.id, false)
      @challeng_questions = Question.where(id: @wrong_answer_reports.pluck(:question_id))
      @right_answer = @reports.joins(:answer).where("answers.correct = ?", true).count if @reports.present?
      @wrong_answer = @reports.joins(:answer).where("answers.correct = ?", false).count if @reports.present?
      @percentage = (@right_answer * 100)/(@questions.count) if @right_answer.present?
      
      @scorecard.update_scorecard if @reports.pluck(:question_id).uniq.count == @questions.count
    end
  end


  def attempted_questions
    @quiz = Quiz.find(params[:id])
    @all_questions = @quiz.questions.active
    @scorecard = current_user.scorecards.find_by_quiz_id(@quiz.id)
    @reports = @scorecard.present? ? @scorecard.reports : []
    @attempted_question = Question.find(params[:question_id])

    if @attempted_question.reports.present?
      @question = @attempted_question
      @report = @scorecard.reports.where(question_id: @question.id).last if @question.present?
    else
      @question = @all_questions.order('id asc').where.not('id in (?)', @reports.pluck(:question_id)).first if @questions.present?
    end
    @wrong_answer_reports = Report.joins(:scorecard, :answer).where("scorecards.user_id = ? and answers.correct = ?", current_user.id, false)
    @challeng_questions = Question.where(id: @wrong_answer_reports.pluck(:question_id))
  end

  def destroy
    quiz = Quiz.find(params[:id])
    scorecard = quiz.scorecards.where(user_id: current_user.id).last
    scorecard.destroy if scorecard.present?
    redirect_to quiz_path(quiz.id)
  end


  def view_questions
    @quiz = Quiz.find(params[:id])
    @all_questions = @quiz.questions.active
    @scorecard = @quiz.scorecards.where(user_id: current_user.id).last
    @reports = @scorecard.reports

    if params[:step].present? && params[:step] == "next"
      @questions = @all_questions.order('id asc').where('id in (?)', @reports.pluck(:question_id))
      @question = @questions.where("id > ?", params[:question_id]).first
    elsif
    params[:question_id].present? && params[:step] == "previous"
      @questions = @all_questions.order('id desc').where('id in (?)', @reports.pluck(:question_id))
      @question = @questions.where("id < ?", params[:question_id]).first
    else
      @questions = @all_questions.order('id asc').where('id in (?)', @reports.pluck(:question_id))
      @question = @questions.first
    end
    @wrong_answer_reports = Report.joins(:scorecard, :answer).where("scorecards.user_id = ? and answers.correct = ?", current_user.id, false)
    @challeng_questions = Question.where(id: @wrong_answer_reports.pluck(:question_id)) if  @wrong_answer_reports.present?
    @report = @scorecard.reports.where(question_id: @question.id).last if @question.present?
  end



  def challenge_bank
    @reports = Report.joins(:scorecard, :answer).where("scorecards.user_id = ? and answers.correct = ?",current_user.id, false)
    @questions = Question.where(id: @reports.pluck(:question_id)).order('id asc')
    if @questions.present?
      if params[:qid].blank?
        @question = @questions.first
      else
        @current_question = Question.where(id: params[:qid]).last
        @next_question = @current_question.next(params[:qid])
        report = Report.where(question_id: @next_question.id).last if @next_question.present?
        if report.present? && !report.answer.correct
          @question = @questions.where(id: params[:qid]).last
          @question = @question.next(params[:qid])
        end
      end
    end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
	def get_quiz_level(quiz_id)
    if current_user.present?
      scorecard = current_user.scorecards.find_by_quiz_id quiz_id
      if scorecard.present?
        return t(".Incomplete")
      else
        quiz = Quiz.find quiz_id
        return quiz.level
      end
    else
      return Quiz::LEVEL[:easy]
    end
  end

	def get_quiz_stat(scorecard_id)
		stat = {}
		scorecard = Scorecard.find scorecard_id
		reports = scorecard.reports.joins(:answer)
		stat[:correct] = reports.where("answers.correct = ?", true).count
		stat[:incorrect] = reports.where("answers.correct = ?", false).count
		return stat
	end


  def get_report_label_color(question_id, quiz_id)
    if current_user.scorecards.present?
      scorecard = current_user.scorecards.where(quiz_id: quiz_id).last
      report = scorecard.reports.where(question_id: question_id).last if scorecard.present?
      return rescue nil if report.blank?
      return report.answer.correct ? "correct-green" : "incorrect-red"
    end
  end


  def get_report_label_for_challenge(question_id)
    report = @reports.where(question_id: question_id).last
    return rescue nil if report.blank?
    return report.answer.correct ? "correct-green" : "incorrect-red"
  end
end

app/views/quizzes/_challenge_bank.html.erb
<div class="test-model clearfix challenge_bank">
  <div class="left-test-side">
    <p class="down-arrow"><i class="fa fa-chevron-down"></i> <%= t("Your Progress")%></p>
    
    <ul class="clearfix progress-rank">
      <% @questions.each_with_index do |question, i| %>
        <% result = get_report_label_for_challenge(question.id) %>
          <li id="<%= question.id %>" class="<%= result %> question_completed"><%= i + 1 %></li>
      <% end %>
    </ul>
    
    <%= link_to(root_path) do %>
      <button class="reset-test"><i class="fa fa-chevron-left"></i> <%= t("Back to the menu") %></button>
    <% end %>
  </div>
  <div class="right-test-side">
    <p class="page-title"><i class="fa fa-check-circle"></i> Your Challenge Bank </p>
    <div class="clearfix test-detail">This is a place where all your missed questions live. Every time you make a mistake in any other mock theory test on our website, that question will appear here, in your Challenge Bank. This is your very own remediation room, another chance to retake those tricky questions and learn from your own mistakes. Good luck!</div>

    <% if @question.present? %>
      <%= hidden_field_tag :current_question, @question.id %>
      <p class="question_bar">
        <%if @question.attachments.present?%>
          <%= image_tag(@question.attachments.last.attachment_url(:thumb).to_s , :class=> "question-img" ) %>
        <%end%>
        <%= @question.title %>
      </p>
      <div class="check-answer">
        <% @question.answers.each do |answer| %>
          <div class="answer-animation">
            <label class="clearfix scorecard challenge-question-<%= @question.id %>"  id="<%= answer.id %>"><span></span> <%= answer.title %></label>
          </div>
        <% end %> 
      </div>
      <div id = "hint">
        <%= @question.hint %>
      </div>
      <p class="next-button disabled"> 
        <%= link_to(challenge_bank_quizzes_path(qid: @question.id)) do %><% end %>
      </p>
      <p class="hint">
        <a href="javascript:void(0)">
        <i class="fa fa-eye-slash"></i><%= t("Hint") %></a>
      </p>
      <p class="progress-bar-increase"></p>
    <%end%>
  </div>
</div>

app/views/quizzes/_next_question.html.erb
<% if @question.present? %>
  <%= hidden_field_tag :current_question, @question.id %>
  <%= hidden_field_tag :current_quiz, @quiz.id %>
  <p class="question_bar"><%= @question.title %></p>
  <div class="check-answer">
    <% @question.answers.each do |answer| %>
      <div class="answer-animation">
        <% if answer.correct %>
          <label class="correct-answer"><span></span> <%= answer.title %></label>
        <% elsif %>
            <% if @report.answer_id == answer.id && answer.correct == false %>
              <label class="wrong-answer"><span></span> <%= answer.title %></label>
            <% else %>
              <label><span></span> <%= answer.title %></label>
            <% end %>
        <% end %>  
      </div>
    <% end %>
  </div>
  <div class="np-buttons">
    <p class="previous-button">
      <%= link_to view_questions_quiz_path(@quiz.id,question_id: @question.id, step: "previous"), class: "previous-button" do %> <% end %>
    </p>
    <p class="next-button"> 
      <%= link_to view_questions_quiz_path(@quiz.id,question_id: @question.id, step: "next"), class: "next-button" do %> <% end %>
    </p>
  </div>
  <p class="hint"><a href="#"><i class="fa fa-eye-slash"></i>Hint</a></p>
  <p class="progress-bar-increase"></p>
<%end%>

<script>

$(document).on('ready', function(){
  $('.check-answer label').addClass('disabled');
  $('.next-button').removeClass('disabled');
});

</script>

app/views/quizzes/_report.html.erb
<div class="fact-sheet">
  <div class="col-md-4 theory-fact">
    <h3>
      <%= t(".DVLA Theory Fact Sheet") %>
    </h3>
    <table>
      <tbody>
        <tr class="odd">
          <td>
            <%= image_tag('help-round-button.png') %> <%= t(".Number of questions") %>:
          </td>
          <td>
            <span class="badge badge-warning"><%= @questions.count%></span>
          </td>
        </tr>
        <tr>
          <td>
            <%= image_tag('checked.png') %><%= t(".Answer correctly to pass")%>:
          </td>
          <td>
            <span class="badge badge-success"><%= @pass_score %></span>
          </td>
        </tr>
        <tr class="odd">
          <td>
            <%= image_tag('check-box.png') %><%= t("Pass mark")%>:
          </td>
          <td>
            <span class="badge badge-info"><%= @passing_percent%> %</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/quizzes/_result.html.erb
<div class="graph-chart">
  <div class="row">
    <div class="col-md-8">
      <% if @right_answer >= @pass_score %>
        <h1 style="color: #60A11F;"><%= t(".You have") %> <strong><%= t(".Passed") %></strong> :)</h1>
      <% else %>  
        <h1 style=""><%= t(".You have") %> <strong><%= t(".Failed") %></strong> :(</h1>
      <% end %> 
      <div id="doughnutChart" class="chart">
        <span class="total_rights"><%= image_tag("correct.png") %><%= @right_answer %> <%=  t(".Correct Answers") %></span>
        <span class="total_wrongs"><%= @wrong_answer %> <%= t(".Wrong Answers") %> <%= image_tag("incorrect.png") %></span>
      </div>
      <ul class = "back_links">  
        <li><%= link_to t(".Restart Test"), quiz_path(@quiz.id), method: :delete %></li>
        <li>|</li>
        <li><%= link_to  t(".View Questions"), view_questions_quiz_path(@quiz.id) %></li>
        <li>|</li>
        <li><%= link_to t(".Go To Your Challenge Bank"), challenge_bank_quizzes_path %></li>
      </ul>
    </div>
    <div class="col-md-4 add-margin-top">
        <%= link_to(root_path) do %>
          <button class="reset-test"><i class="fa fa-chevron-left"></i> <%= t(".Back to the menu") %></button>
        <% end %>
    </div>
  </div>
</div>
 
<script type="text/javascript">
  $( document ).ready(function() {
    setTimeout(function(){
      $(function(){
        $("#doughnutChart").drawDoughnutChart([
          { title: "Tokyo",         value : <%= @right_answer %>,  color: "#5694E6" },
          { title: "San Francisco", value: <%= @wrong_answer %>,   color: "#FF5500" }
        ]);
      });
      ;(function($, undefined) {
        $.fn.drawDoughnutChart = function(data, options) {
          var $this = this,
            W = $this.width(),
            H = $this.height(),
            centerX = W/2,
            centerY = H/2,
            cos = Math.cos,
            sin = Math.sin,
            PI = Math.PI,
            settings = $.extend({
              segmentShowStroke : true,
              segmentStrokeWidth : 1,
              baseOffset: 4,
              edgeOffset : 10,//offset from edge of $this
              percentageInnerCutout : 75,
              animation : true,
              animationSteps : 90,
              animationEasing : "easeInOutExpo",
              animateRotate : true,
              tipOffsetX: -8,
              tipOffsetY: -45,
              tipClass: "doughnutTip",
              summaryClass: "doughnutSummary",
              summaryTitle: "Your Score",
              summaryTitleClass: "doughnutSummaryTitle",
              summaryNumberClass: "doughnutSummaryNumber",
              beforeDraw: function() {  },
              afterDrawed : function() {  },
              onPathEnter : function(e,data) {  },
              onPathLeave : function(e,data) {  }
            }, options),
            animationOptions = {
              linear : function (t) {
                return t;
              },
              easeInOutExpo: function (t) {
                var v = t<.5 ? 8*t*t*t*t : 1-8*(--t)*t*t*t;
                return (v>1) ? 1 : v;
              }
            },
            requestAnimFrame = function() {
              return window.requestAnimationFrame ||
                window.webkitRequestAnimationFrame ||
                window.mozRequestAnimationFrame ||
                window.oRequestAnimationFrame ||
                window.msRequestAnimationFrame ||
                function(callback) {
                  window.setTimeout(callback, 1000 / 60);
                };
            }();

          settings.beforeDraw.call($this);

          var $svg = $('<svg width="' + W + '" height="' + H + '" viewBox="0 0 ' + W + ' ' + H + '" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>').appendTo($this),
              $paths = [],
              easingFunction = animationOptions[settings.animationEasing],
              doughnutRadius = Min([H / 2,W / 2]) - settings.edgeOffset,
              cutoutRadius = doughnutRadius * (settings.percentageInnerCutout / 100),
              segmentTotal = 0;


          //Set up pie segments wrapper
          var $pathGroup = $(document.createElementNS('http://www.w3.org/2000/svg', 'g'));
          $pathGroup.attr({opacity: 0}).appendTo($svg);


          //Set up center text area
          var summarySize = (cutoutRadius - (doughnutRadius - cutoutRadius)) * 2,
              $summary = $('<div class="' + settings.summaryClass + '" />')
                         .appendTo($this)
                         .css({ 
                           width: summarySize + "px",
                           height: summarySize + "px",
                           "margin-left": -(summarySize / 2) + "px",
                           "margin-top": -(summarySize / 2) + "px"
                         });
          var $summaryNumber = $('<p class="' + settings.summaryNumberClass + '"></p>').appendTo($summary).css({opacity: 0});
          var $summaryTitle = $('<p class="' + settings.summaryTitleClass + '">' + settings.summaryTitle + '</p>').appendTo($summary);

          for (var i = 0, len = data.length; i < len; i++) {
            segmentTotal += data[i].value;
            $paths[i] = $(document.createElementNS('http://www.w3.org/2000/svg', 'path'))
              .attr({
                "stroke-width": settings.segmentStrokeWidth,
                "stroke": settings.segmentStrokeColor,
                "fill": data[i].color,
                "data-order": i
              })
              .appendTo($pathGroup)
              .on("mouseenter", pathMouseEnter)
              .on("mouseleave", pathMouseLeave)
              .on("mousemove", pathMouseMove);
          }

          //Animation start
          animationLoop(drawPieSegments);

          //Functions
          function getHollowCirclePath(doughnutRadius, cutoutRadius) {
              //Calculate values for the path.
              //We needn't calculate startRadius, segmentAngle and endRadius, because base doughnut doesn't animate.
              var startRadius = -1.570,// -Math.PI/2
                  segmentAngle = 6.2831,// 1 * ((99.9999/100) * (PI*2)),
                  endRadius = 4.7131,// startRadius + segmentAngle
                  startX = centerX + cos(startRadius) * doughnutRadius,
                  startY = centerY + sin(startRadius) * doughnutRadius,
                  endX2 = centerX + cos(startRadius) * cutoutRadius,
                  endY2 = centerY + sin(startRadius) * cutoutRadius,
                  endX = centerX + cos(endRadius) * doughnutRadius,
                  endY = centerY + sin(endRadius) * doughnutRadius,
                  startX2 = centerX + cos(endRadius) * cutoutRadius,
                  startY2 = centerY + sin(endRadius) * cutoutRadius;
              var cmd = [
                'M', startX, startY,
                'A', doughnutRadius, doughnutRadius, 0, 1, 1, endX, endY,//Draw outer circle
                'Z',//Close path
                'M', startX2, startY2,//Move pointer
                'A', cutoutRadius, cutoutRadius, 0, 1, 0, endX2, endY2,//Draw inner circle
                'Z'
              ];
              cmd = cmd.join(' ');
              return cmd;
          };
          function pathMouseEnter(e) {
            var order = $(this).data().order;
            $tip.text(data[order].title + ": " + data[order].value)
                .fadeIn(200);
            settings.onPathEnter.apply($(this),[e,data]);
          }
          function pathMouseLeave(e) {
            $tip.hide();
            settings.onPathLeave.apply($(this),[e,data]);
          }
          function pathMouseMove(e) {
            $tip.css({
              top: e.pageY + settings.tipOffsetY,
              left: e.pageX - $tip.width() / 2 + settings.tipOffsetX
            });
          }
          function drawPieSegments (animationInteger) {
            var startRadius = -PI / 2,
                rotateAnimation = 1;
            if (settings.animation && settings.animateRotate) rotateAnimation = animationInteger;//count up between0~1

            drawDoughnutText(animationInteger, <%= @percentage %>);

            $pathGroup.attr("opacity", animationInteger);

            //If data have only one value, we draw hollow circle(#1).
            if (data.length === 1 && (4.7122 < (rotateAnimation * ((data[0].value / segmentTotal) * (PI * 2)) + startRadius))) {
              $paths[0].attr("d", getHollowCirclePath(doughnutRadius, cutoutRadius));
              return;
            }
            for (var i = 0, len = data.length; i < len; i++) {
              var segmentAngle = rotateAnimation * ((data[i].value / segmentTotal) * (PI * 2)),
                  endRadius = startRadius + segmentAngle,
                  largeArc = ((endRadius - startRadius) % (PI * 2)) > PI ? 1 : 0,
                  startX = centerX + cos(startRadius) * doughnutRadius,
                  startY = centerY + sin(startRadius) * doughnutRadius,
                  endX2 = centerX + cos(startRadius) * cutoutRadius,
                  endY2 = centerY + sin(startRadius) * cutoutRadius,
                  endX = centerX + cos(endRadius) * doughnutRadius,
                  endY = centerY + sin(endRadius) * doughnutRadius,
                  startX2 = centerX + cos(endRadius) * cutoutRadius,
                  startY2 = centerY + sin(endRadius) * cutoutRadius;
              var cmd = [
                'M', startX, startY,//Move pointer
                'A', doughnutRadius, doughnutRadius, 0, largeArc, 1, endX, endY,//Draw outer arc path
                'L', startX2, startY2,//Draw line path(this line connects outer and innner arc paths)
                'A', cutoutRadius, cutoutRadius, 0, largeArc, 0, endX2, endY2,//Draw inner arc path
                'Z'//Cloth path
              ];
              $paths[i].attr("d", cmd.join(' '));
              startRadius += segmentAngle;
            }
          }
          function drawDoughnutText(animationDecimal, segmentTotal) {
            $summaryNumber
              .css({opacity: animationDecimal})
              .text((segmentTotal * animationDecimal).toFixed(1));
          }
          function animateFrame(cnt, drawData) {
            var easeAdjustedAnimationPercent =(settings.animation)? CapValue(easingFunction(cnt), null, 0) : 1;
            drawData(easeAdjustedAnimationPercent);
          }
          function animationLoop(drawData) {
            var animFrameAmount = (settings.animation)? 1 / CapValue(settings.animationSteps, Number.MAX_VALUE, 1) : 1,
                cnt =(settings.animation)? 0 : 1;
            requestAnimFrame(function() {
                cnt += animFrameAmount;
                animateFrame(cnt, drawData);
                if (cnt <= 1) {
                  requestAnimFrame(arguments.callee);
                } else {
                  settings.afterDrawed.call($this);
                }
            });
          }
          function Max(arr) {
            return Math.max.apply(null, arr);
          }
          function Min(arr) {
            return Math.min.apply(null, arr);
          }
          function isNumber(n) {
            return !isNaN(parseFloat(n)) && isFinite(n);
          }
          function CapValue(valueToCap, maxValue, minValue) {
            if (isNumber(maxValue) && valueToCap > maxValue) return maxValue;
            if (isNumber(minValue) && valueToCap < minValue) return minValue;
            return valueToCap;
          }
          return $this;
        };
      })(jQuery);
    }, 1000);  
  });

</script>

app/views/quizzes/_show.html.erb
<div id="wrapper">
  <article>
    <div class="test-model clearfix">
      <div class="left-test-side">
        <p class="down-arrow"><i class="fa fa-chevron-down"></i><%= t('.Your Progress')%></p>
        
        <ul class="clearfix progress-rank">
          <% @questions.each_with_index do |question, i| %>
            <% result = get_report_label_color(question.id, @quiz.id) %>
              <li id="<%= question.id %>" class="<%= result %> question_completed"><%=  i + 1 %></li>
          <% end %>
        </ul>
        <p class="correct-ans"><%= @pass_score %> <%= t(".correct answers to pass") %> (<%= @mistakes_allowed %> <%= t(".mistakes allowed") %> )</p>
        <%= link_to quiz_path(@quiz.id), method: :delete do %>
          <button class="reset-test"><i class="fa fa-repeat"></i> <%= t(".Restart the test") %></button>
        <% end %>
        
        <p class="change-bank">
          <%= link_to challenge_bank_quizzes_path do %><%= t(".Your Challenge Bank")%> 
            <span class="change-bank-count"><%= @challeng_questions.count %></span>
            <b class="plus-count">+1</b>
          <% end %>
        </p>
        
        <%= link_to(root_path) do %>
          <button class="reset-test"><i class="fa fa-chevron-left"></i><%= t(".Back to the menu") %></button>
        <% end %>
      </div>
      <div class="right-test-side">
        <% if @question.present? %>
          <%= hidden_field_tag :current_question, @question.id %>
          <%= hidden_field_tag :current_quiz, @quiz.id %>
          <p class="question_bar">
            <%if @question.attachments.present?%>
              <%= image_tag(@question.attachments.last.attachment_url(:thumb).to_s , :class=> "question-img" ) %>
            <%end%>
            <%= @question.title %>
          </p>
          <div class="check-answer">
            <% @question.answers.each do |answer| %>
              <div class="answer-animation">
                <label class="clearfix scorecard squestion-<%= @question.id %>"  id="answer_<%= answer.id %>" data-answer="<%= answer.id %>"><span></span> <%= answer.title %></label>
              </div>
            <% end %>
            <div id = "hint">
              <%= @question.hint %>
            </div>
          </div>
          <p class="next-button disabled"> 
            <%= link_to quiz_path do %>
              <%= t(".next_question") %> <i class="fa fa-chevron-right"></i>
            <% end %>
          </p>
          <p class="hint">
            <a href="javascript:void(0)"><i class="fa fa-eye-slash"></i><%= t(".Hint") %></a>
          </p>
          <%= link_to t(".Found a mistake? Let us know!"), new_feedback_path(:locale=> I18n.locale, question_id: @question.id), remote: true %>
          <div class="addthis_inline_share_toolbox"></div>
          <p class="progress-bar-increase"></p>
        <%end%>
      </div>
    </div>
    <div class="fact-theory">
      <%= render 'report'%>
    </div>
  </article>
</div>
<div class="modal fade" id="feedback-modal"></div>

app/views/quizzes/challenge_bank.html.erb
<div id="wrapper">
  <article id = "challenge_bank">
    <%= render "challenge_bank" %>
  </article>
</div>

app/views/quizzes/show.html.erb
<div id= "message"></div>
<% if @reports.pluck(:question_id).uniq.count == @questions.count %>
  <%= render "result" %>
<%else%>
  <%= render "show" %>
<%end%>

<style type="text/css">
	
#message {
	color: #3c763d;
	display: none;
	background-color: #dff0d8;
	border-color: #d6e9c6;
	padding: 15px;
	border-radius: 4px;
	max-width: 1080px;
	font-size: 16px;
	line-height: 16px;
	font-weight: bold;
	margin: 20px auto 0;
	transition: all 0.5s;
}
</style>

app/views/quizzes/view_questions.html.erb
<div id="wrapper">
  <article>
    <div class="test-model clearfix">
      <div class="left-test-side">
        <p class="down-arrow"><i class="fa fa-chevron-down"></i> Your Progress</p>
        
        <ul class="clearfix progress-rank">
          <% @all_questions.each_with_index do |question, i| %>
            <% result = get_report_label_color(question.id, @quiz.id) %>
              <li id="<%= question.id %>" class="<%= result %> question_completed"><%= i + 1 %></li>
          <% end %>
        </ul>
        <p class="correct-ans"><%= @pass_score %> correct answers to pass (<%= @mistakes_allowed %> mistakes allowed)</p>

        <%= link_to quiz_path(@quiz.id) do %>
          <button class="reset-test"><i class=""></i> Back to the Score page </button>
        <% end %>
        <%= link_to quiz_path(@quiz.id), method: :delete do %>
          <button class="reset-test"><i class="fa fa-repeat"></i> Restart the test</button>
        <% end %>
        
        <p class="change-bank">
          <%= link_to challenge_bank_quizzes_path do %>Your Challenge Bank <span class="change-bank-count"><%= @challeng_questions.count rescue 0 %></span>
          <% end %>
        </p>
        
        <%= link_to(root_path) do %>
          <button class="reset-test"><i class="fa fa-chevron-left"></i> Back to the menu</button>
        <% end %>
      </div>
      <div class="right-test-side">

        <%= render "next_question" %>

      </div>
    </div>
  </article>
</div>