config/routes.rb
Rails.application.routes.draw do

  scope ":locale", defaults: {locale: Rails.application.secrets.default_locale}, :path_prefix => '/:locale' do
    ActiveAdmin.routes(self)
  end
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  post "/stripe_webhook" => "memberships#stripe_webhook"
  post "/paypal_webhook" => "memberships#paypal_webhook"
  scope "(:locale)", locale: /ar|en|sv/, defaults: { locale: Rails.application.secrets.default_locale } do
    devise_for :admin_users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users, skip: :omniauth_callbacks
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "home#dashboard"
    post "/hook" => "memberships#hook"

    resources :home do
      collection do
        put 'update_locale'
        get 'leader_board'
      end
    end

    resources :categories do
      collection do
        get 'get_quizzes'
      end
    end
    
    resources :feedbacks
    
    resources :faq_categories do
      member do
        get 'get_questions'
      end
    end
    
    resources :quizzes do
      member do
        get 'attempted_questions'
        get 'view_questions'
      end
      collection do
        get 'challenge_bank'
      end
    end
    
    resources :scorecards
    resources :subscriptions, only: [:new, :create, :index] do
      collection do
        post 'webhook'
      end
    end
    
    resources :reports do
      member do
        patch 'update_report'
      end
    end
    resources :memberships
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user

  def dashboard
    @faq_category = FaqCategory.first
    @faq_questions = @faq_category.faq_questions
    @categories = Category.active.order('id asc')
    @quizzes = @categories.first.quizzes.active if @categories.present?
    @user_reviews = UserReview.all
  end

  def leader_board
    @scorecards = Scorecard.get_leader_board(params[:filter])
  end

  def update_locale
    redirect_back fallback_location: root_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_leader_board.html.erb
<% if scorecards.present? %>
  <% scorecards.each_with_index do |scorecard, index| %>
    <div class="leader-users-btns" >
      <ul>
        <li class="clearfix">
          <div class="rank-number clearfix">
            <%= image_tag "crown.png", alt: "Place", width: "45" %><%= (index+1) %>
          </div>
          <div class="ranker-detail clearfix">
            <div class="ranker-name">
              <%= scorecard['user'].full_name %>
            </div>
            <div class="ranker-ranks-point">
              <span><%= scorecard['score_percentage'].to_f.round(2) %> %</span>
            </div>
          </div>
        </li>
      </ul>
    </div>
  <% end %>
<% else %>
  <div class="text-center">No record found.</div>
<% end %>

app/views/home/dashboard.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-8691613893270336",
    enable_page_level_ads: true
  });
</script>
<article>
  <div class="container theory-text">
    <div class="row">
      <div class="col-md-12">
        <h1><%= t('.Breeze Through Your 2018 DVLA Theory Test')%></h1>
        <div><%= t('.Just like the real thing More effective than the Highway Code')%></div>
        <p class="theory-link down-scroll"><a href="javascript:void(0)"><%= t('.Select your mock theory test') %></a></p>
        <p class="theory-image"><%= image_tag("transport.png")%> </p>
      </div>
      <p class="border-trangle"><span></span></p>
    </div>
  </div>
  <div class="start-test-theory">
    <div class="inner-test-theory">
      <div class="get-ready"><%= t(".Get Ready for Your 2018 DVLA Theory Test Now") %></div>
      <div class="test-topic">
        <ul class="clearfix">
          <% @categories.each do |category| %>
            <li>
              <%= link_to "#{category.quizzes.count} #{category.name}", get_quizzes_categories_path(category_id: category.id) , remote: :true, class: 'car-test active-text' %>
            </li>
          <% end %>
          <li><a class= "faq_scroll" href="javascript:void(0)"><%=t(".UK DVLA FAQ")%></a></li>
          <li><a href="javascript:void(0)"><%=t(".What Our Users Are Saying")%></a></li>
          <li class="border-bar"></li>
        </ul>
      </div>
      <div class = "quiz">
        <%= render "categories/quizzes", :@quizzes => @quizzes   %>
      </div>
      <h2 class="uk-heading"><%= t(".UK Driving Licence Frequently Asked Questions") %></h2>
      <div class="driving_licence">
        <div class="left-licence">
          <p><%= t(".UK Driving Licence FAQ") %></p>
          <ul>
            <% FaqCategory.all.each do |category| %>
              <li class="title" id="category-<%= category.id %>" >
                <%= category.title %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class = "expand-collapse">
          <div class="right-licence">
            <h2 class="question-heading">
              How Can I Get Ready for my UK Driving Theory Test? Frequently Asked Questions
              <p class= 'expand-text'><%= t(".Collapse All") %></p>
            </h2>
            <%if @faq_questions.present?%>
              <% @faq_questions.each do |question| %>
                <ul>
                  <li>
                    <h3 class = "question-link" id = "question_tag-<%=question.id%>"><%= image_tag('question.gif') %><%= question.title %></h3>
                    <div id = "answer-<%= question.id %>" class= "text"><%= question.answer_detail %></div>
                  </li>
                </ul>
              <% end %>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="testimonials">
    <div class="container">
      <div class="section_heading">
        <h2 class="get-ready">What our users are saying</h2>
        <p>Over 15,000 UK learner drivers use TopTests.co.uk daily</p>
      </div>
      <% @user_reviews.each_slice(3) do | user_reviews | %>
        <div class="testimonial_wrapper row">
          <%=render user_reviews %>
        </div>
      <% end %>
    </div>  
  </div>
</article>

<script>

  $(document).ready(function(){
    $(".expand-text").click(function(){
      $(".text").toggle(300);
      if($('.expand-text').text() == "Expand All"){
        $('.expand-text').text("Collapse All")
      }
      else{
        $('.expand-text').text("Expand All")
      }
    });
  }); 

  toggle_effect = function() {
    $(".question-link").click(function(){
      var id = this.id.split('-')[1]
      id = parseInt(id)
      $("#answer-"+id+"").toggle(200);
    });
  };


  $(document).ready(function(){
    toggle_effect()
    $('.left-licence li:first-child').addClass('active_bg')
  });

  $(document).ready(function(){
    $(".title").unbind().click(function() {
      $('.right-licence').html('');
      var category_id = parseInt(this.id.split('-')[1])
      var x = document.getElementsByClassName("active_bg");
      $(x[0]).removeClass('active_bg');
      $(this).addClass('active_bg');
      $.ajax({
        url: "/faq_categories/"+category_id+"/get_questions",
        type: 'GET',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        success: function(response) {
          $(".right-licence").append('<h2 class= "question-heading">'+response.faq_category.heading+' <p class= "expand-text">Collapse All</p></h2>')
          response.faq_questions.forEach(function(faq_question){
            $('.right-licence').append( "<ul><li><h3 class= 'question-link' id = 'question_tag-"+faq_question.id+"'> <img src='/assets/question-4c9f8eeb8672fe9593236021bf5f4eb0d73dfc38fa33624bc77ad6e840d1a817.gif' alt='Question'> " + faq_question.title + "</h3> <div class = 'text' id = 'answer-"+faq_question.id+"'> " + faq_question.answer_detail + " </div></li></ul>")
          });
          toggle_effect()
          $(".expand-text").unbind().click(function(){
            $(".text").toggle(300);
            if($('.expand-text').text() == "Expand All"){
              $('.expand-text').text("Collapse All")
            }
            else{
              $('.expand-text').text("Expand All")
            }
          });
        }
      })    
    });
  });

</script>

<script>
$(document).ready(function(e) {

  $('.test-topic ul li:nth-child(1)').click(function() {
    $('.border-bar').css({
      'left' : '0px',
      'width' : '152px'
    });
  });
  
  $('.test-topic ul li:nth-child(2)').click(function() {
    $('.border-bar').css({
      'left' : '160px',
      'width' : '230px'
    });  
  });
  $(".theory-link").click(function() {
    $('html, body').animate({
        scrollTop: $(".get-ready").offset().top
    }, 1000);
  })

  $('.faq_scroll').click(function(){
    $('html, body').animate({
      scrollTop: $(".uk-heading").offset().top
    }, 500);

  })

});
</script>

</html>

app/views/home/leader_board.html.erb
<article>
	<div class="inner-test-userboard">
		<div class="get-ready marg-top"><%= t('.leader_board') %></div>
		<div class="leader-users">
			<ul id="filters" class="clearfix">
				<li class="active">
					<span class="filter" data-filter="today">
						<%= t('.today_filter') %>
					</span>
				</li>
				<li>
					<span class="filter" data-filter="week">
						<%= t('.week_filter') %>
					</span>
				</li>
				<li>
					<span class="filter" data-filter="month">
						<%= t('.month_filter') %>
					</span>
				</li>
			</ul>
		</div>
		<div id='leader-board'>
			<%= render partial: 'leader_board', locals: { scorecards: @scorecards } %>
		<div>
	</div>
</article>
<script type="text/javascript">
	$(document).ready(function(){
		$('.filter').on('click', function(){
			filter = $(this).data('filter');

			$("#filters li").removeClass("active");
			$(this).parent().addClass("active");
		  return $.ajax({
	      type: "GET",
	      url: "/home/leader_board",
		    data:{ filter: filter },
		    dataType: "script"
		  });
		});

	});
</script>

app/views/home/leader_board.js.erb
$("#leader-board").html("<%= escape_javascript(render partial: 'leader_board', locals: { scorecards: @scorecards } ) %>");