config/routes.rb
Rails.application.routes.draw do

  scope ":locale", defaults: {locale: Rails.application.secrets.default_locale}, :path_prefix => '/:locale' do
    ActiveAdmin.routes(self)
  end
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  post "/stripe_webhook" => "memberships#stripe_webhook"
  post "/paypal_webhook" => "memberships#paypal_webhook"
  scope "(:locale)", locale: /ar|en|sv/, defaults: { locale: Rails.application.secrets.default_locale } do
    devise_for :admin_users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users, skip: :omniauth_callbacks
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "home#dashboard"
    post "/hook" => "memberships#hook"

    resources :home do
      collection do
        put 'update_locale'
        get 'leader_board'
      end
    end

    resources :categories do
      collection do
        get 'get_quizzes'
      end
    end
    
    resources :feedbacks
    
    resources :faq_categories do
      member do
        get 'get_questions'
      end
    end
    
    resources :quizzes do
      member do
        get 'attempted_questions'
        get 'view_questions'
      end
      collection do
        get 'challenge_bank'
      end
    end
    
    resources :scorecards
    resources :subscriptions, only: [:new, :create, :index] do
      collection do
        post 'webhook'
      end
    end
    
    resources :reports do
      member do
        patch 'update_report'
      end
    end
    resources :memberships
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user, only: :create
  skip_before_action :verify_authenticity_token, only: :webhook

  def index
    @plan = Stripe::Plan.all.data
  end

  def new
    plan = Stripe::Plan.retrieve(params[:plan_id])
    @amount = plan.amount/100
  end

  def create
    if current_user.stripe_subscription_id.present?
      flash[:notice] = "Already Subscribed"
      redirect_to root_path and return
    end
    plan = Stripe::Plan.retrieve(params[:plan_id])
    stripe_customer = current_user.stripe_customer_id.present? ? Stripe::Customer.retrieve(current_user.stripe_customer_id) : Stripe::Customer.create(email: params[:stripeEmail], source: params[:stripeToken], description: 'Monthely Subscription')
    stripe_subscription = stripe_customer.subscriptions.create(:plan => plan.id)
    current_user.update_attributes(stripe_subscription_id: stripe_subscription.id, stripe_customer_id: stripe_customer.id)

    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/views/subscriptions/index.html.erb
<% @plan.each do |plan|%>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">
              <%= plan.name%>
            </h3>
          </div>
          <div class="panel-body">
            <table class="table">
              <tr>
                <td>
                  <%= t("Amount") %> - <%= (plan.amount)/100.0 %> $
                </td>
              </tr>
              <tr class="active">
                <td>
                  <%= t("Currency") %> - <%= plan.currency %>
                </td>
              </tr>
            </table>
          </div>
          <div class="panel-footer">
          <% if !current_user.stripe_subscription_id.present? %>
            <%= link_to t("Subscribe"), new_subscription_path(plan_id: plan.id) , class: "btn btn-success" %>
          <%else%>
            <span class="color"><%= t("Already Subscribed") %> </span> 
          <% end %>  
            </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/subscriptions/new.html.erb
<div class="payment_form">
  <p>You Need to subscribe your account.</p>

  <%= form_tag subscriptions_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount" style="margin: 10px 0;">
        <span>Amount: <%= @amount %></span>
      </label>
    </article>

    <%= hidden_field_tag :plan_id,  params[:plan_id] %>

    <%= hidden_field_tag :subscription, value: params[:subscription] %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
            data-description="<%= @description %>"
            data-amount="<%= (@amount*100) %>"
            data-email="<%= current_user.email %>"
            data-bitcoin="true"
            data-locale="auto"></script>
  <% end %>
</div>