config/routes.rb
Rails.application.routes.draw do

  scope ":locale", defaults: {locale: Rails.application.secrets.default_locale}, :path_prefix => '/:locale' do
    ActiveAdmin.routes(self)
  end
  
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  post "/stripe_webhook" => "memberships#stripe_webhook"
  post "/paypal_webhook" => "memberships#paypal_webhook"
  scope "(:locale)", locale: /ar|en|sv/, defaults: { locale: Rails.application.secrets.default_locale } do
    devise_for :admin_users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users, skip: :omniauth_callbacks
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "home#dashboard"
    post "/hook" => "memberships#hook"

    resources :home do
      collection do
        put 'update_locale'
        get 'leader_board'
      end
    end

    resources :categories do
      collection do
        get 'get_quizzes'
      end
    end
    
    resources :feedbacks
    
    resources :faq_categories do
      member do
        get 'get_questions'
      end
    end
    
    resources :quizzes do
      member do
        get 'attempted_questions'
        get 'view_questions'
      end
      collection do
        get 'challenge_bank'
      end
    end
    
    resources :scorecards
    resources :subscriptions, only: [:new, :create, :index] do
      collection do
        post 'webhook'
      end
    end
    
    resources :reports do
      member do
        patch 'update_report'
      end
    end
    resources :memberships
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="pageTop"> <%= link_to "#{image_tag('up-arrow.png')}".html_safe, "javascript:void(0)" %></a><br>PageTop</div>
  <div id="footer">
    <p id="copyright">copyright &copy;</p>
  </div>
</footer>

app/views/layouts/_secure_header.html.erb
<header>
  <div id="header">
    <div id="headerIn" class="clearfix">
      <h1 id="headerLogo"><%= link_to t('.DriveExam'), root_path %></a></h1>
      <a href="#menu" class="menu-link active"><span></span></a>
      <nav id="gNavi" class="visiblePC menu">
        <ul class="level-1">
          <li id="gNav01"><a href="#"><%= t('.Highway Code') %></a></li>
          <li id="gNav02"><a href="#"> <%= t('.Hazard Perception Test') %></a></li>
          <!-- <li id="gNav03"><a href="#"> <%#= t('.Driving Tips') %></a></li> -->
          <li id="gNav04">
            <%= link_to t('.leader_board'), leader_board_home_index_path %>
          </li>
          <% if @current_user.present? %>
            <% if !@current_user.guest %>
              <li id="gNav01"><%= link_to t(".Membership"), memberships_path, method: :get %></li>
              <li id="gNav01"><%= link_to t(".profile"), edit_user_registration_path, method: :get %></li>
              <li id="gNav01"><%= link_to t(".Logout"), destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li id="gNav01"><%= link_to t(".Sign-In"), new_user_session_path, method: :post %></li>
              <li id="gNav01"><%= link_to t(".Sign-Up"), new_user_registration_path %></li>
            <% end %>
          <% end %>
          <li>
            <a href="#" role="button" class="dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= t('.Language') %></a>
            <span class="has-subnav">&#x25BC;</span>
            <ul class="wide level-2">
              <li><%= link_to "English", url_for(locale: :en) %></li>
              <li><%= link_to "العربى", url_for(locale: :ar) %></li>
              <li><%= link_to "svenska", url_for(locale: :sv) %></li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
 </header>
<style type="text/css">
.js .menu > ul li:hover > ul{ margin-top: -15px; margin-left: -9px; border-radius:0px 5px 5px 5px; }
html body ul.wide.level-2 li:hover a{ color: #000 !important; }
.menu-link span { display: inline-block; }
.menu, .menu > ul, .menu > ul ul { display: flex; flex-flow: column; }
.menu.active { max-height: 55em; width: 94vw; }
.js .menu > ul ul.active { max-height: 55em; }
nav li { display: inline-block; position: relative; }
.menu li a { display: inline-block; }
span.has-subnav { display: block; position: absolute; right: 0px; top: 0; text-align:right; }
@media screen and (max-width:800px) {
.menu, .menu > ul ul { margin: 0; max-height: 0; overflow: hidden; }
.menu li a { display: block; }
}
@media screen and (min-width: 801px) {
a.menu-link { display: none; }
.js .menu, .js .menu > ul ul { max-height: none; overflow: visible; }
.js .menu > ul li:hover > ul { display: flex; }
.menu ul { display: flex; flex-flow: row; height: 44px; justify-content: space-between; margin: 0; padding: 0; }
.menu span.has-subnav { display: none; }
.menu ul ul { display: none; height: auto; overflow: hidden; position: absolute; text-align: left; top: 43px; width: 150px; z-index: 999; }
.chrome .js .menu > ul ul { top: 43px; }
.menu ul ul.wide { width: 250px; }
.menu ul ul li { display: inline-block; position: relative; }
.menu ul ul li a { display: block; }
}

</style>
<script>
// Multi-Toggle Navigation
$(function() {
  $('body').addClass('js');
    var $menu = $('.menu'),
      $menulink = $('.menu-link'),
      $menuTrigger = $('.has-subnav');

  $menulink.click(function(e) {
    e.preventDefault();
    $menulink.toggleClass('active');
    $menu.toggleClass('active');
  });

  $menuTrigger.click(function(e) {
    e.preventDefault();
    var $this = $(this);
    $this.toggleClass('active').next('ul').toggleClass('active');
  });

});

// Remove "Active" Class from Menu on Resize
$(window).resize(function() {
  var viewportWidth = $(window).width();
    if (viewportWidth > 925) {
      $(".menu").removeClass("active");
    }
});

</script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DriveExam</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= hidden_field_tag :locale, I18n.locale  %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5abe4a1ca8ce735f"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/secure_header'%>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <% if I18n.locale.to_s == "ar" %>
      <%= stylesheet_link_tag 'rtl', media: 'all' %>
    <% end %>
  </body>
</html>